server: 
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: estudiante-service
          uri: lb://estudiante-service
          predicates:
            - Path=/estudiante/**
        - id: curso-service
          uri: lb://curso-service
          predicates:
            - Path=/curso/**
        - id: tutoria-service
          uri: lb://tutoria-service
          predicates:
            - Path=/tutoria/**
      
